version: "3.9"

services:
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres_db
    environment:
      PGADMIN_DEFAULT_EMAIL: userrepository@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
